### PR TITLE
add systemd unit file

### PR DESCRIPTION
**Pull request by bmanojlovic**
I have added very simple systemd unit file, please provide info where would you like it to be located in source tree as i put it now directly into root.
```
pc:~ # systemctl start leprechaun.service 
pc:~ # systemctl status leprechaun.service 
● leprechaun.service - Leprechaun service
   Loaded: loaded (/etc/systemd/system/leprechaun.service; disabled; vendor preset: disabled)
   Active: active (running) since Tue 2018-10-30 19:16:02 CET; 1s ago
 Main PID: 21163 (leprechaun)
    Tasks: 11 (limit: 4915)
   CGroup: /system.slice/leprechaun.service
           └─21163 /usr/bin/leprechaun

Oct 30 19:16:02 pc.djule.org systemd[1]: Started Leprechaun service.
pc:~ # 
pc:~ # 
```

### CODE REVIEW

**Comment by kilgaloon** [comment]
Hey, thanks for PR, this looks nice, for now it can reside on root side, I’m little familiar with systems but keep in mind that leprechaun is installed on system running ‘make install’ which setups everything on user system, regarding **leprechaun.service** for example where it should be located on system?

**Comment by bmanojlovic** [comment]
it can be run as user and every time user is logged in but that is again exact problem with systemd user level services - it will be stopped when user logs out. :\

**Comment by kilgaloon** [comment]
Since Leprechaun is intended to be used on server have no problem of users loggin out. I will merge this

**Comment by bmanojlovic** [comment]
wait please now it is very much intrusive please check before doing merge :)

**Pull request closed without merging**
